---
# Handlers for tileserver role
- name: restart tileserver
  systemd:
    name: tileserver-ram.service
    state: restarted
    daemon_reload: yes

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
