---
mbtiles_files:
  - /home/shantanu/Documents/Software/tileserver-gl_inst/india-latest.mbtiles
  - /home/shantanu/Documents/Software/tileserver-gl_inst/zurich_switzerland.mbtiles
persistent_mbtiles_dir: /var/lib/tileserver/mbtiles
ramdisk_mount_point: /mnt/tileserver-mbtiles
# default ramdisk_size left empty to enable automatic detection via Ansible facts; the role will compute 1/3 of RAM
ramdisk_size: ''
tileserver_user: tileserver
tileserver_port: 8080

# Style rewrite defaults
# Mapping of source name in the upstream style -> MBTiles basename (without .mbtiles)
style_source_mapping:
  versatiles-shortbread: india-latest
# If input_style is empty the rewire script will fetch the upstream style from the default URL
style_input: ''
# path on control where the generated style will be written
style_output_path: web/local1-versatiles/colorful_style_local.json
# where to deploy the generated style and web files on the target host
style_deploy_dir: /var/lib/tileserver/web
style_deploy_subdir: local1-versatiles
# enable or disable automatic rewire and deployment as part of the role
style_rewrite_enabled: true
